### ISSUE TITLE
Dreamcast fails to launch game from Openmenu

### ISSUE THREAD

**Issue by TechnoNT** [mrneo240/openmenu#1]
Tested games from all three regions but all show the same issue.

https://user-images.githubusercontent.com/83992138/123433126-684ebc80-d5cb-11eb-9aa2-eb391a617237.mov

**Comment by Drakonas** [comment]
I have the same issue. Posted the report here, but I suppose it was better fit for here: 
https://github.com/mrneo240/GDMENUCardManager/issues/6

**Comment by mrneo240** [comment]
Fix incoming by friday 7/2

**Comment by FlorreW** [comment]
I also have this problem.  Tested the latest version.

Console: Ntsc-J  

Will test on my Pal machine this evening to see if it makes any difference.

**Comment by Drakonas** [comment]
Can confirm the 07-05 update fixed the issue.

**Comment by mrneo240** [comment]
Thank you for revisiting and commenting!
Please check the latest version + metadata. It should fix strange issues showing for vmu block size among other changes.
