### ISSUE TITLE
Street Fighter Alpha 3 (PAL) Boxart

### ISSUE THREAD

**Issue by cdf83** [mrneo240/openmenu#12]
Street Fighter Alpha 3 (PAL) has the box art for Plasma Sword (PAL).
![16275419007853811071786710878343](https://user-images.githubusercontent.com/75204866/127446346-509b1422-8088-4e5a-b9b3-916401539e36.jpg)

**Comment by mrneo240** [comment]
Noted and will be corrected. Thank you

**Comment by mrneo240** [comment]
Fixed under #15
