### ISSUE TITLE
Black Screen After Initial Boot

### ISSUE THREAD

**Issue by RalphJB12** [mrneo240/openmenu#13]
The Dreamcast boots into a black screen after initial Dreamcast swirl when booting up. VMU shows openmenu on its screen but my TV is black. I followed the installation instructions to a "T." I am using a clone gdemu. Could that be the reason? 

EDIT: I also happen to be using an NTSC-U Dreamcast with composite cable.

**Comment by RalphJB12** [comment]
I have a theory that it may just be displaying at a resolution not supported over composite cables on my Sony 4K TV. If this is the case, any ideas how I can change the resolution?

**Comment by aaaaafuck** [comment]
Same thing for me using both VGA and composite on multiple TVs. I also tried multiple SD cards. Normal GDMenu works fine with both SD cards and both video outputs. I am using and an official GDEMU. Don't know why it doesn't work really wanted to try it out.

**Comment by mrneo240** [comment]
I only own VGA cables for my dreamcast.

For this to be fixed someone with composite cables will have to contribute or donate a set to me.

**Comment by RalphJB12** [comment]
I'd also like to mention that I have some PAL and NTSC-J games on there. Not sure if that would make any difference or affect anything.

**Comment by mrneo240** [comment]
Any chance you could attempt booting openMenu without a vmu in your controller 1?

**Comment by regulardude400** [comment]
Hey I also got a black screen here is my setup.

Laptop:
OS Linux Mint 20.2 Cinnamon
GDEMU Card Manager version: https://github.com/mrneo240/GDMENUCardManager/releases/download/1.3.3-openmenu/linux-x64.zip

Dreamcast: NTSC-U/C
DCDigital firmware version: 4.9
GDEMU: Official but unsure of the firmware version.

Things I have tried but have resulted in Black screen with flashing green line across screen:
Tried with VMU card inserted and not inserted.
Tried to force VGA mode output

**Comment by mrneo240** [comment]
Okay. This is proving to be very tricky indeed. I still don't quite understand what is going wrong

Can you please upload your OPENMENU.INI file from the folder you run GDEMUCardManager.

**Comment by regulardude400** [comment]
> Okay. This is proving to be very tricky indeed. I still don't quite understand what is going wrong
> 
> Can you please upload your OPENMENU.INI file from the folder you run GDEMUCardManager.
> 
> I apologize for the hassle but I just can't replicate

No problem.  I was apparently not running a compatible version of GDEMUCardManager. Because after I got the latest release on July 6th 2021, it worked first try after loading up the program, hitting save, and then putting the card on my Dreamcast.  

Thanks so much! For anyone else having issues, when in doubt, be sure to download the latest release folks: https://github.com/mrneo240/GDMENUCardManager/releases and it might work just fine.

**Comment by mrneo240** [comment]
great to hear. @regulardude400 
Im going to keep this open until i hear from @RalphJB12

**Comment by RalphJB12** [comment]
Sorry. Just saw this. Gonna try this method today. I'll post with results.

**Comment by RalphJB12** [comment]
> > Okay. This is proving to be very tricky indeed. I still don't quite understand what is going wrong
> > Can you please upload your OPENMENU.INI file from the folder you run GDEMUCardManager.
> > I apologize for the hassle but I just can't replicate
> 
> No problem. I was apparently not running a compatible version of GDEMUCardManager even though mine said 1.3.3. I say this because after I got the latest release on July 6th 2021, it worked first try after loading up the program, hitting save, and then putting the card on my Dreamcast.
> 
> Thanks so much! For anyone else having issues, when in doubt, be sure to download the latest release folks: https://github.com/mrneo240/GDMENUCardManager/releases and it might work just fine. The menu is really pretty!

Hi all, 

I managed to fix the issue by following the steps above. It's very important to ensure that you are using updated and current versions of all the apps or you will run into the black screen issues. OPENMENU works perfectly for me now. So thankful to everyone's advice and to @mrneo240 for this wonderful interface. Looking forward to further updates and hope to have art and description for all NTSC-J, Indie, and Atomiswave games.

**Comment by mrneo240** [comment]
> NTSC-J, Indie, and Atomiswave games.

Atmosiwave is completed.
Ntscj is slowly getting more coverage 82/650
Indie/homebrew will be left to the community but I'm not sure yet how to coordinate

**Comment by adamfratino** [comment]
I've been running into a black screen and an openmenu logo on the VMU while trying multiple video inputs too. I'm using [GDMENUCardManager.v1.3.5-osx-x64-AppBundle.tar.gz](https://github.com/sonik-br/GDMENUCardManager/releases/tag/v1.3.5) on OSX 10.15.7 and manually adding openmenu after right-clicking the app and choosing "Show Package Contents". I've tried both `openmenu_7-05-21.zip` and `openmenu_12-5-2021_alpha2.zip` with `DAT_12-5-21.zip` but no luck.

I only got my GDEmu a couple weeks ago so this was my first attempt.

**Comment by stry8993** [comment]
I'm having the issue described. This says its closed, but, its March 4th and its still going.

I have a VA1 NTSC-U Dreamcast with a Clone 5.15b GDEmu

I have tried with 1.3.3 and 1.3.5

I've tried with no VMU in slot 1. I've tried with only 1 controller plugged in and nothing else.

Using VGA Cables from thefoo.83 and a Sandisk Extreme 256GB MicroSD.

**Comment by psychosb** [comment]
@mrneo240, I'm having the same problem that the user above.

I have a VA1 NTSC-U Dreamcast with a Clone 5.15b GDEmu
I have tried with 1.3.3 and 1.3.5 and with no VMU in slot 1. I've tried with only 1 controller plugged in and nothing else.

Any tips?
