### ISSUE TITLE
[Issue, boxarts] Mismatch with PAL games

### ISSUE THREAD

**Issue by IlDucci** [mrneo240/openmenu#15]
Alone in the Dark The New Nightmare and Crazy Taxi have the NTSC-U covers displayed on their PAL versions.

I'm using the latest DAT file (DAT_7-20-21).

![IMG_0165](https://user-images.githubusercontent.com/5641681/138093842-c781e026-22bd-484f-b226-70a6167b6831.JPG)

**Comment by mrneo240** [comment]
please share ini file or serials of those games. 

Thank you

**Comment by IlDucci** [comment]
Hmmm, the plot thickens. According to both Redump and my game's cover, the serial for AITD4 should be T-15112D-05A. But the actual serial in the GDI is T-15117N, the USA equivalent.

PAL disc: http://redump.org/disc/47733/
NTSC-U disc: http://redump.org/disc/24762/

(See the Header section)

Same thing happens with Crazy Taxi: they share the BOOT serial.

PAL disc: http://redump.org/disc/9648/
NTSC-U disc: http://redump.org/disc/18037/

**Comment by mrneo240** [comment]
Alright this might have to be handled at the GDMenuCardManager level since it appears to be functioning as intended at the openMenu level.

**Comment by mrneo240** [comment]
Thinking more but I'm away from my laptop to verify, I think the ini does store region info and if so could be handled on load

**Comment by mrneo240** [comment]
Fixed and a 5 others with similar issues were found as well.

**Comment by IlDucci** [comment]
Unless the final release has something the latest alpha doesn't, file DAT_12-1-21.zip still displays the USA boxarts.

**Comment by mrneo240** [comment]
Please attach OPENMENU.INI from GDMenuCardManager folder so I can replicate your environment and test what isn't working.

**Comment by IlDucci** [comment]
Here you go
[OPENMENU.zip](https://github.com/mrneo240/openmenu/files/7644856/OPENMENU.zip)
.

**Comment by mrneo240** [comment]
Forgot to add the rest of the overrides in, now added all games I've found with overlapping serials.
Including crazy taxi, plasma sword, alone in the dark, nightmare creatures
