### ISSUE TITLE
[Bug Report] PAL games are not working or having issues at 50 Hz

### ISSUE THREAD

**Issue by IlDucci** [mrneo240/openmenu#17]
I have tried to switch from GDMENU to OpenMenu + your fork of GDMenuCardManager and boot the games I had on my SD card. All of those games are GDIs pre-ReDump or CDI. All of them are PAL versions.

**None of them work properly at 50 Hz.** Some games (Alone In The Dark, Soldier of Fortune, Crazy Taxi) just don't boot, they simply go to a black screen followed by a reboot of the OpenMenu. Others, (Resident Evil 2, Shenmue I, Shenmue II) manage to boot properly, but the video mode selection screen is displayed with the wrong method, outputting a B/W image with the wrong colors until I select the 60Hz mode.

![IMG_0166](https://user-images.githubusercontent.com/5641681/138094696-dd12fbda-36d5-43df-8719-18bb37f4f654.JPG)
![IMG_0167](https://user-images.githubusercontent.com/5641681/138094700-6b49df6a-19b2-45fc-9ff6-51a4d56b5671.JPG)

I'm using an old GDEMU, a v5.4 from 2014, recently updated to the latest firmware. I have confirmed that all these discs work correctly with the original GDMENU v0.6.

**Comment by mrneo240** [comment]
I dont own any PAL dc hardware or displays. 

This will have to be fixed by someone who does or is willing to donate all of it

**Comment by IlDucci** [comment]
If that's the case, I'd strongly recommend adding a big, nice warning on the README file and the main page of the site.

**Comment by mrneo240** [comment]
Ill try to possibly fix but I have no way of testing

**Comment by megavolt85** [comment]
> I have tried to switch from GDMENU to OpenMenu + your fork of GDMenuCardManager and boot the games I had on my SD card. All of those games are GDIs pre-ReDump or CDI. All of them are PAL versions.
> 
> **None of them work properly at 50 Hz.** Some games (Alone In The Dark, Soldier of Fortune, Crazy Taxi) just don't boot, they simply go to a black screen followed by a reboot of the OpenMenu. Others, (Resident Evil 2, Shenmue I, Shenmue II) manage to boot properly, but the video mode selection screen is displayed with the wrong method, outputting a B/W image with the wrong colors until I select the 60Hz mode.
> 
> ![IMG_0166](https://user-images.githubusercontent.com/5641681/138094696-dd12fbda-36d5-43df-8719-18bb37f4f654.JPG) ![IMG_0167](https://user-images.githubusercontent.com/5641681/138094700-6b49df6a-19b2-45fc-9ff6-51a4d56b5671.JPG)
> 
> I'm using an old GDEMU, a v5.4 from 2014, recently updated to the latest firmware. I have confirmed that all these discs work correctly with the original GDMENU v0.6.

test with last update

**Comment by IlDucci** [comment]
I have tested the latest alpha from Dreamcast-Talk.com, named openmenu_12-1-21_alpha.

All the mentioned games now work correctly, both those that did not boot at all and those that booted, but were being displayed incorrectly under 50 Hz. I guess you can confirm now that PAL (Europe) games work fine.

Great work!

**Comment by mrneo240** [comment]
Excellent. Please don't hesitate to file more issues if any arise. A full release will land soon
