### ISSUE TITLE
wrong game loading in OpenMenu launcher

### ISSUE THREAD

**Issue by uberdisko** [mrneo240/openmenu#18]
i have been trying to play Zombie Revenge and for whatever reason it loads the wrong game, im not sure if i have too many games or am doing something wrong but i double checked in GDMENUManager and it seemed to load the correct image there (popping that numbered file into RetroArch), everything worked fine on the stock GDemu menu

**Comment by mrneo240** [comment]
I believe this is an issue currently happening with sd cards using over 255 games. 
It is being working on currently.

**Comment by uberdisko** [comment]
did you fix the 255 game limit?

**Comment by mrneo240** [comment]
Yes in an alpha update not yet posted here
