### ISSUE TITLE
Fighting Force 2 missing from Metadata

### ISSUE THREAD

**Issue by Drakonas** [mrneo240/openmenu#2]
Game Name: FIGHTING FORCE 2
CRC: 97DB
Product ID: 36801N V1.000
Maker ID: SEGA ENTERPRISES
Hardware ID: SEGA SEGAKATANA
Compagny name: 
Release date: 1999/12/17
Supported area: USA
VGA box supported: Yes

![IP.BIN](http://mercury.whatbox.ca:42424/img/GD-ROM_Explorer_2021-07-02_19-37-50.png)

**Comment by mrneo240** [comment]
Correct Database Product ID
