### ISSUE TITLE
multidisc numbered icon

### ISSUE THREAD

**Issue by binarygeek119** [mrneo240/openmenu#20]
on multidisc it be nice to have a small icon tha says disc # over the cover image 

just a quick simple i made
![Untitled-2](https://user-images.githubusercontent.com/72405030/144833120-005a658e-c472-4fa6-9ddb-5c042043a177.jpg)

**Comment by mrneo240** [comment]
It does above the game name. 
The version in the screenshot is 6 months old. Please follow the instructions to update
