### ISSUE TITLE
VGA mode force

### ISSUE THREAD

**Issue by RalphJB12** [mrneo240/openmenu#21]
Is it possible to force VGA mode the same way you can in gdmenu? It's not allowing me to do so and I can't get Dino Crisis to work. 

Seven Mansions is also displaying a black screen with no audio or visual.

**Comment by megavolt85** [comment]
forced VGA is already enabled, it removes BIOS check
if the game does not support VGA, then no menu will fix it
for Dino Crisis there is a special patched version of the GDI image from japanese-cake
Seven Mansions with VGA support no

**Comment by mrneo240** [comment]
Unfortunately yup, the above comment is correct

**Comment by RalphJB12** [comment]
> forced VGA is already enabled, it removes BIOS check if the game does not support VGA, then no menu will fix it for Dino Crisis there is a special patched version of the GDI image from japanese-cake Seven Mansions with VGA support no

I'm already using the special patched version of Dino Crisis and it worked fine on GDmenu. Seven Mansions also worked perfectly on GDmenu. Now neither game works. I'll try and redownload and install both to see if that fixes the issue.

**Comment by megavolt85** [comment]
> 

then you are the first person in the world to have Seven Mansions running in VGA mode :D

**Comment by RalphJB12** [comment]
> > 
> 
> then you are the first person in the world to have Seven Mansions running in VGA mode :D

Lol. Bruh, I'm not joking. I really did have it running, previously. I personally tested every game I had when I first got the GDEMU and GDMENU to ensure they all worked. This included Seven Mansions. And yes, it was running on my VGA cable. Like I said, I'll redownload it and see if I can get it to work again. Really don't want to have to swap cables or go back to GDMENU, because I really like the OPENMENU interface.

**Comment by megavolt85** [comment]
> Seven Mansions

I'm not kidding either, Seven Mansions doesn't work at 480p
either you did not run it through VGA, or you used a TV / monitor / scaler that supports 480i mode

**Comment by RalphJB12** [comment]
I'm ashamed to admit that the Mandela Effect had me fucked up. You are both correct. I never had the game running in VGA. When I first ran the game, it was using the svideo cables that came with the same. I apologize. 

I totally forgot that the Gekko box wasn't something I bought until after I got the Dreamcast. All those initial tests for games were using that svideo cable.
