### ISSUE TITLE
All box art is missing

### ISSUE THREAD

**Issue by dylanwinn** [mrneo240/openmenu#22]
Sorry if this is the wrong place to ask this, please direct me to a forum if there is one.

I have an SD card previously set up with GDEMU which I am trying to convert to openMenu. I followed the instructions on the wiki and everything seems to be working fine, except that *all* of the box art is missing and just shows a placeholder image. The name, description and other metadata shows up just fine. Am I doing something wrong?

**Comment by mrneo240** [comment]
I believe you skipped the step where you download and extract the DAT files into the GDMENUCardManager data folders. 
Please reread.

**Comment by mrneo240** [comment]
Pulse check. Closing Friday, feel free to reopen another.

**Comment by dylanwinn** [comment]
I was able to resolve this by using the windows version of GDMENUCardManager instead of the OSX version. So either I did something wrong the first time, or this is a bug specifically in the osx-x64 build of mrneo240/GDMENUCardManager version 1.3.3-openMenu. I'll open an issue there instead.

**Comment by mrneo240** [comment]
Thank you!
