### ISSUE TITLE
The Ghost Blade: the game reboot after the opening

### ISSUE THREAD

**Issue by legolas119** [mrneo240/openmenu#27]
Hi, i have an issue with the .cdi image of The Ghost Blade. The game boot, but after the opening, the game reboot and it appears again the Game select screen of OpenMenu.

Is it possible to fix it?
thanks!

**Comment by legolas119** [comment]
i solved the issue, i used a bad dump, now the game works perfectly

**Comment by smzlivee** [comment]
I've also met this problem, and I haven't solved it yet. I've met this problem with several versions of cdi that I've downloaded，May I ask how you solved it?

**Comment by legolas119** [comment]
well i tried a different version and it worked, it seems that that version works...

**Comment by smzlivee** [comment]
Do you still have the version of cdi file that worked? Could you share it ?

**Comment by legolas119** [comment]
yes, but i think i can't share it here..

**Comment by smzlivee** [comment]
> yes, but i think i can't share it here..

Could you send it to my email? smzwindows@outlook.com

**Comment by legolas119** [comment]
yes, sent!

**Comment by smzlivee** [comment]
> yes, sent!

Thanks, I've received the file.
