### ISSUE TITLE
The King of Fighters NeoWave Atomiswave port: doesn't boot correctly, only sound

### ISSUE THREAD

**Issue by legolas119** [mrneo240/openmenu#28]
Hi,
i tried The King of Fighters NeoWave, the Atomiswave port, but unfortunately it doesn't boot correctly. After several seconds, there is only a black screen and it is available only sound.

Thank you

**Comment by megavolt85** [comment]
your problem has nothing to do with the menu

**Comment by legolas119** [comment]
ah ok, is it an issue related to GDEMU...does anyone has same issue?

**Comment by legolas119** [comment]
i solved the issue: the game works but it is mandatory not to use the latest update (2021-12-12).  It works only with the previous update (2021-01-11).
