### ISSUE TITLE
Numbered folders > 255 do not load properly

### ISSUE THREAD

**Issue by Horganic** [mrneo240/openmenu#29]
**Describe the bug**
Numbered folders are used for each game, starting at 02 (01 is reserved for GD/open Menu).  If you get up to folder '256' or higher, the games do not load properly.  In fact, they appear to load other games on the SD card as if it was an overflow bug on the folder number being treated as an unsigned byte.

**To Reproduce**
1. Fill the SD game with game folders.
2. Make note of the game in folder '256'
3. Try to laugh that game from openMenu
4. You will get a different game, or possibly openMenu itself again.

**Expected behavior**
Games in folders above 256 should work properly.  They do with the original GDMenu v0.6

**Comment by megavolt85** [comment]
> 

are you sure you are using the latest openmenu version?
this bug was fixed in the latest update

**Comment by Horganic** [comment]
I can confirm the issue is resolved in 2021-12-5_alpha2.  Thank you!
