### ISSUE TITLE
Rayman 2 missing from metadata

### ISSUE THREAD

**Issue by Drakonas** [mrneo240/openmenu#3]
Game Name: RAYMAN 2 THE GREAT ESCAPE
CRC: D97E
Product ID: 17707N V1.003
Maker ID: SEGA ENTERPRISES
Hardware ID: SEGA SEGAKATANA
Compagny name: 177
Release date: 2000/02/22
Supported area: USA
VGA box supported: Yes

![IP.BIN](http://mercury.whatbox.ca:42424/img/GD-ROM_Explorer_2021-07-02_19-37-26.png)

**Comment by mrneo240** [comment]
Correct Database Product ID
