### ISSUE TITLE
[BOXART] Game Title missing boxart/metadat

### ISSUE THREAD

**Issue by Dead694** [mrneo240/openmenu#32]
## T46605D
Hello, I noticed that there are no metadat and boxarts for the EvilTwin game, I also looked at the META.DAT file and did not find the required ID. Hello from Russia, thanks for your development work! Sorry for my English)

SEGA SEGAKATANA 
SEGA ENTERPRISES
F6E0 GD-ROM1/1  
  E     0799810 
T46605D 71V1.001
20020109        
1ST_READ.BIN    
SEGA LC-T-466   
EVILTWIN

**Comment by mrneo240** [comment]
noted and will be added in future DATs.
Thank you!
