### ISSUE TITLE
Please wee need an asset editor

### ISSUE THREAD

**Issue by alfchk** [mrneo240/openmenu#39]
Please wee need an asset editor.
to make some meta translate. and add missings meta.
to add missing covers. so many after market games have no cover (and for few games who have needed name changing like kof... King of, the king of... to have all in the same place these games have needed renaming...)
to correct cover error like hokuto no ken.
please help us

**Comment by mrneo240** [comment]
Feel free to write one or to use the existing one created by sonik-br.

Additionally,  all metadata and coverart issues will be here handled here:

https://github.com/mrneo240/openMenu_imagedb

https://github.com/mrneo240/openMenu_metadb
