### ISSUE TITLE
Install without use of GDMENUCardManager? 

### ISSUE THREAD

**Issue by tomasz-nolberczak** [mrneo240/openmenu#4]
Hey! Is it possible to install the openMenu on SD card without making use of GDMENUCardManager? Will it be enough to put contents to `01` folder?

PS: Thanks for your hard work 🙏🏻!

**Comment by mrneo240** [comment]
Currently It will not, it requires specific setup prior to running your gdemu. 

Later after the base of the application is done I can look into running with zero config and a longer loading screen.

**Comment by mrneo240** [comment]
If part of the issue is running or using GDMENUCardManager I would be glad to try and assist you in getting that running.
