### ISSUE TITLE
Is it possible to add folders to the browsing?

### ISSUE THREAD

**Issue by aaaaafuck** [mrneo240/openmenu#42]
In the original dreamcast list view is it possible to add folders to make sorting your game library easier?
Here are some use case examples:

Region Sorting:
├── NTSC-U
│   ├── Crazy Taxi (USA copy)
│   └── Daytona USA (USA copy)
│   └── Who Wants to Beat Up a Millionaire (USA exclusive)
├── PAL
│   ├── Crazy Taxi (PAL copy)
│   └── Toy Racer (PAL exclusive)
├── JP
│   ├── Air (JP exclusive)
│   └── Daytona USA (JP copy)

Genre Sorting:
├── Driving
│   ├── Crazy Taxi (USA)
│   └── Daytona USA (USA)
│   └── F1 World Grand Prix II for Dreamcast (PAL)
├── Fighting
│   ├── Marvel vs. Capcom - Clash of Super Heroes (USA)
│   └── Marvel vs. Capcom 2 (USA)
├── RPG
│   ├── deSPIRIA (JP)
│   └── Skies of Arcadia (Disc 1) (USA)
│   └── Skies of Arcadia (Disc 2) (USA)

Sorting Translations/Romhacks Away from Original Copies
├── Official Games
│   ├── Napple Tale - Arsia in Daydream (JP)
│   └── Rent A Hero No.1 (JP)
│   └── Taxi 2 - The Game (PAL)
├── Translations
│   ├── Napple Tale - Arsia in Daydream (English by Cargodin v1.0)
│   └── Rent A Hero No.1 (English v1.0)
│   └── Taxi 2 - The Game (English - v1.0)

**Comment by mrneo240** [comment]
Yes. Feature is started just unfinished currently. 

It will be an extension of the genre feature but allow personal arbitrary folders. Hang tight

**Comment by megavolt85** [comment]
> In the original dreamcast list view is it possible to add folders to make sorting your game library easier? 
https://github.com/megavolt85/openmenu/releases/tag/openmenu_28.10.23

**Comment by aaaaafuck** [comment]
> > https://github.com/megavolt85/openmenu/releases/tag/openmenu_28.10.23
I tried it out it works fantastic! Thank you for the update.

These are the things I noticed that I think maybe should be changed though depending on your opinion:

- I think it would be easier to navigate the folder view if the b button took you back to the previous folder.

- Lowercase letters make the sorting incorrect inside the folder (this is easy to fix on my end, so not that big of a deal)

![vcs_zoAIGPhfHG](https://github.com/mrneo240/openmenu/assets/43722742/6efdad92-2b9f-4def-aba0-17dc6fd5bcae)

- As mrneo240 mentioned in his comment I think it would be cool if you were able to define the categories for each game yourself in some way.

**Comment by megavolt85** [comment]
1) button B is already busy, it is assigned to launch codebreaker
2) I will easily correct it
3) Unfortunately, for this need create new tool and make another user database

**Comment by aaaaafuck** [comment]
1. I don't know how used the folder feature will be by people other than me, but if there is other people that bring this up maybe exit to bios (Y) could be moved inside the Menu (X). I wouldn't want to ruin usability for other people if you think it is more important that has its own button.
2. Thank you
3. I understand, I am curious if that is what mrneo had originally planned on doing.
