### ISSUE TITLE
Can’t open settings in openmenu

### ISSUE THREAD

**Issue by tamasjantek** [mrneo240/openmenu#44]
I got the newest release from card manager and from openmenu, and I can’t open settings in the UI. If I press start it just reorganize the titles. Is there any way to open the settings window?

thanks

**Comment by aaaaafuck** [comment]
The openmenu from the card manager is out of date. If you replace the files from the latest release in this repository and then rerun then card manager it will update and you will no longer have this problem.

**Comment by tamasjantek** [comment]
> The openmenu bundled with the card manager is out of date. If you replace the files from the latest release in this repository and then rerun then card manager it will update and you will no longer have this problem.

Solved it, thanks for the fast reply!

**Comment by mrneo240** [comment]
That is in the instructions but perhaps a notice at the top would be useful.
