### ISSUE TITLE
[Feature request] Button to leave to Dreamcast main menu

### ISSUE THREAD

**Issue by Drakonas** [mrneo240/openmenu#5]
I realize this is alpha, so I'm not asking for immediate additions, but this is purely for tracking purposes.

It would be nice not to have to take the SD card out to be able to get to the Dreamcast main menu to manage VMU files.

**Comment by mrneo240** [comment]
Good idea.
Planned to implement with addition of menu and credits screen.

**Comment by mrneo240** [comment]
Implemented exit on options screen
